# Generated by Django 5.2.5 on 2025-08-13 12:27

import django.db.models.deletion
import recycler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='recycler.category')),
            ],
        ),
        migrations.CreateModel(
            name='RecyclingCentre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.FloatField(validators=[recycler.models.validate_latitude])),
                ('longitude', models.FloatField(validators=[recycler.models.validate_longitude])),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('tags', models.CharField(max_length=100)),
                ('accepted_categories', models.ManyToManyField(related_name='recycling_centres', to='recycler.category')),
            ],
        ),
    ]
