# Generated by Django 5.2.4 on 2025-08-13 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recycler', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('voucher_id', models.AutoField(primary_key=True, serialize=False)),
                ('discount_amt', models.DecimalField(decimal_places=2, max_digits=6)),
                ('name', models.CharField(max_length=100)),
                ('points', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='vouchers/')),
                ('claimed_count', models.IntegerField(default=0)),
                ('claimable_count', models.IntegerField(default=1)),
                ('expiration_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('recycle_center_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recycler.recyclingcentre')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tier')),
            ],
        ),
        migrations.CreateModel(
            name='VoucherInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('redeemed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rewards.voucher')),
            ],
        ),
    ]
