# Generated by Django 5.2.4 on 2025-08-13 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=255)),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField(blank=True, null=True)),
                ('weight', models.CharField(blank=True, max_length=50, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('labels', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecyclableIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('plastic', 'Plastic'), ('paper', 'Paper'), ('cardboard', 'Cardboard'), ('glass', 'Glass'), ('metal', 'Metal'), ('e-waste', 'E-Waste')], max_length=100)),
                ('subcategory', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'unique_together': {('category', 'subcategory')},
            },
        ),
    ]
